[package]
name = "opentelemetry-tonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.17" }
tonic = "0.8"
tracing = "0.1"
tracing-opentelemetry = "0.17"
